# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - dev
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
    export SHELL=/bin/bash
    pnpm setup
  displayName: 'Install and Setup pnpm'

- script: |
    pnpm install
    pnpm run build
  displayName: 'Build Next.js application'

- script: |
    pnpm run test
  displayName: 'Run Tests'
  condition: eq(variables['Build.SourceBranchName'], 'refs/heads/dev')

- script: |
    pnpm install -g firebase-tools
    firebase deploy --only hosting
  displayName: 'Deploy to Firebase Hosting'
  condition: eq(variables['Build.SourceBranchName'], 'refs/heads/main')
  env:
    FIREBASE_TOKEN: $(FIREBASE_TOKEN)
    SHELL: /bin/bash