import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import { cookies } from 'next/headers';
import { SESSION_COOKIE_NAME } from './utils/constants';
import Providers from "./components/providers/Providers"
import NavMenu from "./components/NavMenu";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = cookies().get(SESSION_COOKIE_NAME)?.value || null;

  return (
    <html lang="es">
      <body className={inter.className}>
        <Providers session={session}>
          <NavMenu />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
