import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import { cookies } from 'next/headers';
import { SESSION_COOKIE_NAME } from './utils/constants';
import Providers from "./components/providers/Providers"
import NavMenu from "./components/NavMenu";
import Footer from "./components/Footer";
import { fetchUserInfo } from "./libs/firebase/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = cookies().get(SESSION_COOKIE_NAME)?.value || null;
  const initialTheme = cookies().get('theme')?.value || null;
  
  // Get the initial user if there is a session
  let initialUser = null;
  if (session) {
    try {
      initialUser = await fetchUserInfo(session);
    } catch (error) {
      console.error('Error al obtener el usuario inicial:', error);
    }
  }

  return (
    <html lang="es" className={initialTheme === 'dark' ? 'dark' : ''}>
      <body className={inter.className}>
        <Providers 
          session={session} 
          initialTheme={initialTheme}
          initialUser={initialUser}
        >
          <NavMenu />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
